### ISSUE TITLE
How to change the threadx main frequency?

### ISSUE THREAD

**Issue by Barfell** [STMicroelectronics/stm32_mw_threadx#1]
As the title, how to change the threadx's clock when the system is run. sometimes, need very low clock, to save power.

**Comment by Barfell** [comment]
Hi @ALABSTM 

In FREERTOS, We can do as fellow，to change main clock source，works normally. We need to implement the same functionality in ThreadX。

void Normal_Sysclock(void)
{
	__HAL_RCC_MSI_RANGE_CONFIG(RCC_MSIRANGE_7);
	__NOP();
	__NOP();	
	
	__HAL_FLASH_SET_LATENCY(FLASH_LATENCY_0);
	__HAL_RCC_PWR_CLK_ENABLE();

	HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE2);
	SystemCoreClockUpdate();
	vPortSetupTimerInterrupt();	/////////////////////////////////////////////////////////////////////
}
void HighSpeed_Sysclock(void)
{
	__HAL_RCC_MSI_RANGE_CONFIG(RCC_MSIRANGE_11);
	__NOP();
	__NOP();	

	__HAL_FLASH_SET_LATENCY(FLASH_LATENCY_2);	
	__HAL_RCC_PWR_CLK_ENABLE();

	HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);
	SystemCoreClockUpdate();
	vPortSetupTimerInterrupt();	/////////////////////////////////////////////////////////////////
}

**Comment by ALABSTM** [comment]
Hi @Barfell,

At first glance, there is no direct equivalent in *TheadX* of *FreeRTOS*'s `vPortSetupTimerInterrupt()`. However, you could call `HAL_SYSTICK_Config()` instead. You can find its definition and more information about it in the [stm32u5xx_hal_cortex.c](https://github.com/STMicroelectronics/stm32u5xx_hal_driver/blob/5313c6919f88e8ec4212da91bbe1146d4262d44c/Src/stm32u5xx_hal_cortex.c#L50-L74) file, for instance.

I hope this helps. In the meanwhile, we will dig this question deeper and get back to you as soon as we have further to share.

With regards,

**Comment by ALABSTM** [comment]
Hi @Barfell,

Any feedback please? Were the above indications helpful?

With regards,

**Comment by Barfell** [comment]
> Hi @Barfell,
> 
> Any feedback please? Were the above indications helpful?
> 
> With regards,

I will complete the development of the device function first, and then consider the issue of power consumption, thank you.

**Comment by ALABSTM** [comment]
Hi @Barfell,

I hope you are fine. I hope the above indications were helpful. Please allow me to close this thread as no feedback received since a couple of weeks. Thank you for your comprehension.

With regards,
