### ISSUE TITLE
Windows 11 says DISTRO stm32-mw-threadx has a virus

### ISSUE THREAD

**Issue by Atticus-X** [STMicroelectronics/stm32_mw_threadx#2]
FYI, when downloading using Windows 11, MS Edge says DISTRO stm32-mw-threadx has a virus.
( It does not appear to have infected anyone yet )!!!

Please advise.

![Screenshot 2024-12-12 204308 Threadx](https://github.com/user-attachments/assets/6e2c010b-6b60-4ed8-ba1e-97d214d00780)

**Comment by Atticus-X** [comment]
Works, solid!

**Comment by ALABSTM** [comment]
Hi @Atticus-X,

Glad to read this was a false positive. Thank you for the notification.

With regards,
